---
title: "Sumár kontraktov v Centrálnom registry zmlúv SR"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: bootstrap
  runtime: shiny
---

```{r, global, setup}
library(flexdashboard)
library(here)
library(shiny)
#file = source(here::here("crz", "common", "crz_db_con.R"), local = knitr::knit_global())
file = source(here::here("crz", "crz_summary.R"), local = knitr::knit_global())
```

# Page 1

## Row 1 {.sidebar}

### Menu

> Vyerte dátum

```{r}
selectInput( "n_breaks", label = "Number of bins:", choices = c(10, 20, 35, 50), selected = 20 )
```

## Row

### Total contracts amount

```{r}
flexdashboard::valueBox(paste(crz_contracts_summary$Contracts.Amount, "mld€", sep = ""), caption = "Celková hodnota zmlúv", icon="fa-tag")
```

### Average contract size

```{r}
flexdashboard::valueBox(paste(crz_contracts_summary$Aver.Contract.Size,"€", sep = ""), caption = "Priemerná hodnota kontraktu", icon = "fa-comments")
```

## Row

### Biggest contract amount

```{r}
flexdashboard::valueBox(paste(crz_contracts_summary$Max.Contract.Size, "mld€", sep = ""), caption = "Najväčší kontrakt", icon="fa-tag")
```

### Total contract quantity

```{r}
flexdashboard::valueBox(crz_contracts_summary$Contracts.Quantity, caption = "Celkový počet kontraktov", icon = "fa-comments")
```

## Row

### contractors quantity

```{r}
flexdashboard::valueBox(crz_contracts_summary$Contractors.Quantity, caption = "Počet zadávateľov", icon = "fa-comments")
```

### Suppliers quantity

```{r}
flexdashboard::valueBox(crz_contracts_summary$Suppliers.Quantity, caption = "Počet dodávateľov", icon = "fa-comments")
```

# Zgroj dát

## Riadok 1

### Zdrojové dáta

```{r fig_height=10}
DT::datatable(crz_contracts_summary_flipped_sk) 
```

# Test

## Riadok


### Tu bude tabuľka

sddsdsdsdsd



```{r}
library(kableExtra)
crz_contracts_summary_flipped_sk %>%
  kbl() %>%
  kable_classic(full_width = F, position = "left", html_font = "Cambria")
```

### Tabuľka 2



```{r}
library(kableExtra)
crz_contracts_summary_flipped_sk %>%
  kbl() %>%
  kable_classic(full_width = F, position = "left", html_font = "Cambria")
```
