---
title: "Najväčšie kontrakty"
always_allow_html: yes
output:
  flexdashboard::flex_dashboard:
    number_sections: yes
    orientation: rows
    vertical_layout: scroll
    theme:
      version: 4
      bootswatch: minty
---

```{r}
# file=c('common/crz_db_con.R', 'crz_top_contracts.R')
#
# setwd("D:/R/Projects/Web/use-cases/crz")
#source('common/crz_db_con.R', local = knitr::knit_global())
#source('crz_top_contracts.R', local = knitr::knit_global())
```



```{r, global, setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(stringr)
library(dplyr)
#load("data/crz_top_contracts_100_basic.Rdata")
load("data/crz_top_contracts_100.Rdata")
```

## First row {.tabset}

### Table 


```{r}
library(kableExtra)
#crz_top_contracts_100$Subject <- str_trunc(crz_top_contracts_100$Subject, 75, "right")
crz_top_contracts_100[1:25,] %>%
  select(Contract.ID, Contractor, Supplier, Subject, Price) %>%
  rename("Contract ID" = Contract.ID,
         "Price[m€]" = Price) %>%
  mutate(
    Contractor = str_trunc(Contractor, 40, "right"),
    Supplier = str_trunc(Supplier, 40, "right"),
    Subject = str_trunc(Subject, 40, "right")
   ) %>%
  kbl(align = "llllc") %>%
  kable_classic(full_width = F, html_font = "Cambria", bootstrap_options = c("condensed", "hover", "striped"), position = "left") %>%
  column_spec(5, color = "white", background = spec_color(mtcars$drat[1:8], end = 0.7))
```




### Treemap Chart

```{r fig.width=12, fig.height=10, fig.cap = "An amazing plot"}
library(treemap)
 # treemap(
 #   crz_top_contracts_100_basic,
 #   index="Subject",
 #   vSize="Price",
 #   type="index")
```

